import json
from importlib import resources

_JSON_DIR = resources.files(__package__).joinpath("xml_mapping_jsons")


def _load(filename: str):
    return json.loads(_JSON_DIR.joinpath(filename).read_text(encoding="utf-8-sig"))



XML_MAPPING_DICTS_BY_TYPE = {
    "INFORMATION TABLE": _load("informationtable.json"),
    "QUALIF" : _load("qualif.json"),
    "EFFECT" : _load("effect.json"),
    "25-NSE" : _load("25nse.json"),
    "25-NSE/A" : _load("25nse.json"),
    "C-TR" : _load("ctr.json"), 
    "C-TR-W" : _load("ctr.json"),
    "X-17A-5" : _load("x17a5.json"),
    "X-17A-5/A" : _load("x17a5.json"),
    "1-K" : _load("1k.json"),
    "1-K/A" : _load("1k.json"),
    "D" :  _load("d.json"),
    "D/A" :  _load("d.json"),
    "N-PX" :  _load("npx.json"),
    "N-PX/A" :  _load("npx.json"),
    "144" :  _load("144.json"),
    "144/A" :  _load("144.json"),
    "SCHEDULE 13D" :  _load("schedule13d.json"),
    "SCHEDULE 13D/A" :  _load("schedule13d.json"),
    "SCHEDULE 13G"   : _load("schedule13g.json"),
    "SCHEDULE 13G/A" : _load("schedule13g.json"),
    "1-Z" :  _load("1z.json"),
    "1-Z/A" :  _load("1z.json"),
    "1-A" :  _load("1a.json"),
    "1-A/A" :  _load("1a.json"),
    "1-A POS" :  _load("1a.json"),
    "DOS":   _load("dos.json"),
    "DOS/A": _load("dos.json"),
    "13F-HR" : _load("13fhr.json"),
    "13F-HR/A" : _load("13fhr.json"),
    "13F-NT" : _load("13fhr.json"),
    "13F-NT/A" : _load("13fhr.json"),
    "PROXY VOTING RECORD" : _load("proxyvotingrecord.json"),
    "COVER PAGE": _load("coverpage.json"),
    "N-CR" : _load("ncr.json"),
    "24F-2NT"   : _load("24f2nt.json"),
    "24F-2NT/A" : _load("24f2nt.json"),
    "SH-ER" : _load("sher.json"),
    "SDR"   : _load("sdr.json"),
    "SDR/A" : _load("sdr.json"),
    "CFPORTAL"   : _load("cfportal.json"),
    "CFPORTAL/A" : _load("cfportal.json"),
    "CFPORTAL-W" : _load("cfportal.json"),
    "EX-103" : _load("ex103.json"),
    "EX-102" : _load("ex102.json"),
    "4" : _load("345.json"),
    "4/A" : _load("345.json"),
    "3" : _load("345.json"),
    "3/A" : _load("345.json"),
    "5" : _load("345.json"),
    "5/A" : _load("345.json"),
    "MA-I" : _load("mai.json"),
    "MA-I/A" : _load("mai.json"),
    "NPORT-P" : _load("nportp.json"),
    "NPORT-P/A" : _load("nportp.json"),
    "TA-2" : _load("ta2.json"),
    "TA-2/A" : _load("ta2.json"),
    "N-MFP2" : _load("nmfp12.json"),
    "N-MFP2/A" : _load("nmfp12.json"),
    "C-U" : _load("c.json"),
    "C-U-W" : _load("c.json"),
    "TA-1" : _load("ta1.json"),
    "TA-1/A" : _load("ta1.json"),
    "N-CEN" : _load("ncen.json"),
    "N-CEN/A" : _load("ncen.json"),
    "N-MFP" : _load("nmfp.json"),
    "N-MFP/A" : _load("nmfp.json"),
    "MA" : _load("ma.json"),
    "MA/A" : _load("ma.json"),
    "C/A" : _load("c.json"),
    "C/A-W" : _load("c.json"),
    "MA-A" : _load("ma.json"),
    "MA-W" : _load("maw.json"),
    "N-MFP1" : _load("nmfp12.json"),
    "N-MFP1/A" : _load("nmfp12.json"),
    "C-W" : _load("c.json"),
    "C-AR/A" : _load("c.json"),
    "C-AR-W" : _load("c.json"),
    "C" : _load("c.json"),
    "N-MFP3" : _load("nmfp3.json"),
    "N-MFP3/A" : _load("nmfp3.json"),
    "TA-W" : _load("taw.json"),
    "ATS-N/UA" : _load("atsn_ua.json"),
    "ATS-N-W" : _load("atsn_ua.json"),
    "ATS-N-C" : _load("atsn_ua.json"),
    "ATS-N/OFA" : _load("atsn_ua.json"),
    "ATS-N/CA" : _load("atsn_ua.json"),
    "ATS-N/MA" : _load("atsn_ua.json"),
    "C-AR" : _load("c.json"),
    "SBSE-C" : _load("sbsec.json"),
    "SBSE" : _load("sbsec.json"),
    "SBSE/A" : _load("sbsec.json"),
    "SBSE-A" : _load("sbsec.json"),
    "SBSE-A/A" : _load("sbsec.json"),
    "SBSE-BD" : _load("sbsec.json"),
    "SBSE-BD/A" : _load("sbsec.json"),
    "SBSE-W" : _load("sbsec.json"),
    "SBSEF" : _load("sbsec.json"),
    "SBSEF/A" : _load("sbsec.json"),
    "SBSEF-W" : _load("sbsec.json"),
}
