mapping_metadata_345 = {
    'dateOfOriginalSubmission' :'dateOfOriginalSubmission',
    'documentType' :'documentType',
    'form3HoldingsReported' :'form3HoldingsReported',
    'form4TransactionsReported' :'form4TransactionsReported',
    'issuer_issuerCik' : 'issuerCIK',
    'issuer_issuerName' :'issuerName',
    'issuer_issuerTradingSymbol' :'issuerTradingSymbol',
    'noSecuritiesOwned' :'noSecuritiesOwned',
    'schemaVersion' : 'schemaVersion',
    'notSubjectToSection16' :'notSubjectToSection16',
    'ownerSignature' :'ownerSignature',
    'ownerSignature_signatureDate' : 'ownerSignatureDate',
    'ownerSignature_signatureName' : 'ownerSignatureName',
    'periodOfReport' : 'periodOfReport',
    'remarks' : 'remarks',
    'reportingOwner_reportingOwnerAddress_rptOwnerCity' : 'reportingOwnerCity',
    'reportingOwner_reportingOwnerAddress_rptOwnerState' : 'reportingOwnerState',
    'reportingOwner_reportingOwnerAddress_rptOwnerStateDescription' : 'reportingOwnerStateDescription',
    'reportingOwner_reportingOwnerAddress_rptOwnerStreet1' : 'reportingOwnerStreet1',
    'reportingOwner_reportingOwnerAddress_rptOwnerStreet2' : 'reportingOwnerStreet2',
    'reportingOwner_reportingOwnerAddress_rptOwnerZipCode' : 'reportingOwnerZipCode',
    'reportingOwner_reportingOwnerId_rptOwnerCik' : 'reportingOwnerCIK',
    'reportingOwner_reportingOwnerId_rptOwnerName' : 'reportingOwnerName',
    'reportingOwner_reportingOwnerRelationship_isDirector' : 'reportingOwnerIsDirector',
    'reportingOwner_reportingOwnerRelationship_isOfficer' : 'reportingOwnerIsOfficer',
    'reportingOwner_reportingOwnerRelationship_isOther' : 'reportingOwnerIsOther',
    'reportingOwner_reportingOwnerRelationship_isTenPercentOwner' : 'reportingOwnerIsTenPercentOwner',
    'reportingOwner_reportingOwnerRelationship_officerTitle' : 'reportingOwnerOfficerTitle',
    'reportingOwner_reportingOwnerRelationship_otherText' : 'reportingOwnerOtherText',
}

mapping_nonderivative_holdings_345 = {
    'ownershipNature_directOrIndirectOwnership_footnote': 'directOrIndirectOwnershipFootnote',
    'ownershipNature_directOrIndirectOwnership_value': 'directOrIndirectOwnership',
    'ownershipNature_natureOfOwnership_footnote': 'natureOfOwnershipFootnote',
    'ownershipNature_natureOfOwnership_value': 'natureOfOwnership',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_footnote': 'sharesOwnedFollowingTransactionFootnote',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_value': 'sharesOwnedFollowingTransaction',
    'securityTitle_footnote': 'securityTitleFootnote',
    'securityTitle_value': 'securityTitle',
    'transactionCoding_footnote': 'transactionCodingFootnote',
    'transactionCoding_transactionFormType': 'transactionFormType'
}

mapping_nonderivative_transactions_345 = {
    'deemedExecutionDate_footnote': 'deemedExecutionDateFootnote',
    'deemedExecutionDate_value': 'deemedExecutionDate',
    'ownershipNature_directOrIndirectOwnership_footnote': 'directOrIndirectOwnershipFootnote',
    'ownershipNature_directOrIndirectOwnership_value': 'directOrIndirectOwnership',
    'ownershipNature_natureOfOwnership_footnote': 'natureOfOwnershipFootnote',
    'ownershipNature_natureOfOwnership_value': 'natureOfOwnership',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_footnote': 'sharesOwnedFollowingTransactionFootnote',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_value': 'sharesOwnedFollowingTransaction',
    'postTransactionAmounts_valueOwnedFollowingTransaction_value': 'valueOwnedFollowingTransaction',
    'securityTitle_footnote': 'securityTitleFootnote',
    'securityTitle_value': 'securityTitle',
    'transactionAmounts_transactionAcquiredDisposedCode_footnote': 'transactionAcquiredDisposedCodeFootnote',
    'transactionAmounts_transactionAcquiredDisposedCode_value': 'transactionAcquiredDisposedCode',
    'transactionAmounts_transactionPricePerShare_footnote': 'transactionPricePerShareFootnote',
    'transactionAmounts_transactionPricePerShare_value': 'transactionPricePerShare',
    'transactionAmounts_transactionShares_footnote': 'transactionSharesFootnote',
    'transactionAmounts_transactionShares_value': 'transactionShares',
    'transactionCoding_equitySwapInvolved': 'equitySwapInvolved',
    'transactionCoding_footnote': 'transactionCodingFootnote',
    'transactionCoding_transactionCode': 'transactionCode',
    'transactionCoding_transactionFormType': 'transactionFormType',
    'transactionDate_footnote': 'transactionDateFootnote',
    'transactionDate_value': 'transactionDate',
    'transactionTimeliness_footnote': 'transactionTimelinessFootnote',
    'transactionTimeliness_value': 'transactionTimeliness'
}

mapping_derivative_holdings_345 = {
    'conversionOrExercisePrice_footnote': 'conversionOrExercisePriceFootnote',
    'conversionOrExercisePrice_value': 'conversionOrExercisePrice',
    'exerciseDate_footnote': 'exerciseDateFootnote',
    'exerciseDate_value': 'exerciseDate',
    'expirationDate_footnote': 'expirationDateFootnote',
    'expirationDate_value': 'expirationDate',
    'ownershipNature_directOrIndirectOwnership_footnote': 'directOrIndirectOwnershipFootnote',
    'ownershipNature_directOrIndirectOwnership_value': 'directOrIndirectOwnership',
    'ownershipNature_natureOfOwnership_footnote': 'natureOfOwnershipFootnote',
    'ownershipNature_natureOfOwnership_value': 'natureOfOwnership',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_footnote': 'sharesOwnedFollowingTransactionFootnote',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_value': 'sharesOwnedFollowingTransaction',
    'postTransactionAmounts_valueOwnedFollowingTransaction_value': 'valueOwnedFollowingTransaction',
    'securityTitle_footnote': 'securityTitleFootnote',
    'securityTitle_value': 'securityTitle',
    'transactionCoding_transactionFormType': 'transactionFormType',
    'underlyingSecurity_underlyingSecurityShares_footnote': 'underlyingSecuritySharesFootnote',
    'underlyingSecurity_underlyingSecurityShares_value': 'underlyingSecurityShares',
    'underlyingSecurity_underlyingSecurityTitle_footnote': 'underlyingSecurityTitleFootnote',
    'underlyingSecurity_underlyingSecurityTitle_value': 'underlyingSecurityTitle'
}

mapping_derivative_transactions_345 = {
    'conversionOrExercisePrice_footnote': 'conversionOrExercisePriceFootnote',
    'conversionOrExercisePrice_value': 'conversionOrExercisePrice',
    'deemedExecutionDate_footnote': 'deemedExecutionDateFootnote',
    'deemedExecutionDate_value': 'deemedExecutionDate',
    'exerciseDate_footnote': 'exerciseDateFootnote',
    'exerciseDate_value': 'exerciseDate',
    'expirationDate_footnote': 'expirationDateFootnote',
    'expirationDate_value': 'expirationDate',
    'ownershipNature_directOrIndirectOwnership_footnote': 'directOrIndirectOwnershipFootnote',
    'ownershipNature_directOrIndirectOwnership_value': 'directOrIndirectOwnership',
    'ownershipNature_natureOfOwnership_footnote': 'natureOfOwnershipFootnote',
    'ownershipNature_natureOfOwnership_value': 'natureOfOwnership',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_footnote': 'sharesOwnedFollowingTransactionFootnote',
    'postTransactionAmounts_sharesOwnedFollowingTransaction_value': 'sharesOwnedFollowingTransaction',
    'postTransactionAmounts_valueOwnedFollowingTransaction_footnote': 'valueOwnedFollowingTransactionFootnote',
    'postTransactionAmounts_valueOwnedFollowingTransaction_value': 'valueOwnedFollowingTransaction',
    'securityTitle_footnote': 'securityTitleFootnote',
    'securityTitle_value': 'securityTitle',
    'transactionAmounts_transactionAcquiredDisposedCode_value': 'transactionAcquiredDisposedCode',
    'transactionAmounts_transactionPricePerShare_footnote': 'transactionPricePerShareFootnote',
    'transactionAmounts_transactionPricePerShare_value': 'transactionPricePerShare',
    'transactionAmounts_transactionShares_footnote': 'transactionSharesFootnote',
    'transactionAmounts_transactionShares_value': 'transactionShares',
    'transactionAmounts_transactionTotalValue_footnote': 'transactionTotalValueFootnote',
    'transactionAmounts_transactionTotalValue_value': 'transactionTotalValue',
    'transactionCoding_equitySwapInvolved': 'equitySwapInvolved',
    'transactionCoding_footnote': 'transactionCodingFootnote',
    'transactionCoding_transactionCode': 'transactionCode',
    'transactionCoding_transactionFormType': 'transactionFormType',
    'transactionDate_footnote': 'transactionDateFootnote',
    'transactionDate_value': 'transactionDate',
    'transactionTimeliness_footnote': 'transactionTimelinessFootnote',
    'transactionTimeliness_value': 'transactionTimeliness',
    'underlyingSecurity_underlyingSecurityShares_footnote': 'underlyingSecuritySharesFootnote',
    'underlyingSecurity_underlyingSecurityShares_value': 'underlyingSecurityShares',
    'underlyingSecurity_underlyingSecurityTitle_footnote': 'underlyingSecurityTitleFootnote',
    'underlyingSecurity_underlyingSecurityTitle_value': 'underlyingSecurityTitle'
}

mapping_metadata_13f = {
    'formData_coverPage_additionalInformation': 'additionalInformation',
    'formData_coverPage_amendmentInfo_amendmentType': 'amendmentType',
    'formData_coverPage_amendmentInfo_confDeniedExpired': 'confDeniedExpired',
    'formData_coverPage_amendmentInfo_dateDeniedExpired': 'dateDeniedExpired',
    'formData_coverPage_amendmentInfo_dateReported': 'dateReported',
    'formData_coverPage_amendmentInfo_reasonForNonConfidentiality': 'reasonForNonConfidentiality',
    'formData_coverPage_amendmentNo': 'amendmentNo',
    'formData_coverPage_crdNumber': 'crdNumber',
    'formData_coverPage_filingManager_address_city': 'filingManagerCity',
    'formData_coverPage_filingManager_address_stateOrCountry': 'filingManagerStateOrCountry',
    'formData_coverPage_filingManager_address_street1': 'filingManagerStreet1',
    'formData_coverPage_filingManager_address_street2': 'filingManagerStreet2',
    'formData_coverPage_filingManager_address_zipCode': 'filingManagerZipCode',
    'formData_coverPage_filingManager_name': 'filingManagerName',
    'formData_coverPage_form13FFileNumber': 'form13FFileNumber',
    'formData_coverPage_isAmendment': 'isAmendment',
    'formData_coverPage_otherManagersInfo_otherManager': 'otherManager',
    'formData_coverPage_otherManagersInfo_otherManager_cik': 'otherManagerCik',
    'formData_coverPage_otherManagersInfo_otherManager_crdNumber': 'otherManagerCrdNumber',
    'formData_coverPage_otherManagersInfo_otherManager_form13FFileNumber': 'otherManagerForm13FFileNumber',
    'formData_coverPage_otherManagersInfo_otherManager_name': 'otherManagerName',
    'formData_coverPage_otherManagersInfo_otherManager_secFileNumber': 'otherManagerSecFileNumber',
    'formData_coverPage_provideInfoForInstruction5': 'provideInfoForInstruction5',
    'formData_coverPage_reportCalendarOrQuarter': 'reportCalendarOrQuarter',
    'formData_coverPage_reportType': 'reportType',
    'formData_coverPage_secFileNumber': 'secFileNumber',
    'formData_signatureBlock_city': 'signatureCity',
    'formData_signatureBlock_name': 'signatureName',
    'formData_signatureBlock_phone': 'signaturePhone',
    'formData_signatureBlock_signature': 'signature',
    'formData_signatureBlock_signatureDate': 'signatureDate',
    'formData_signatureBlock_stateOrCountry': 'signatureStateOrCountry',
    'formData_signatureBlock_title': 'signatureTitle',
    'formData_summaryPage_isConfidentialOmitted': 'isConfidentialOmitted',
    'formData_summaryPage_otherIncludedManagersCount': 'otherIncludedManagersCount',
    'formData_summaryPage_otherManagers2Info_otherManager2': 'otherManager2',
    'formData_summaryPage_otherManagers2Info_otherManager2_otherManager_cik': 'otherManager2CIK',
    'formData_summaryPage_otherManagers2Info_otherManager2_otherManager_crdNumber': 'otherManager2CrdNumber',
    'formData_summaryPage_otherManagers2Info_otherManager2_otherManager_form13FFileNumber': 'otherManager2Form13FFileNumber',
    'formData_summaryPage_otherManagers2Info_otherManager2_otherManager_name': 'otherManager2Name',
    'formData_summaryPage_otherManagers2Info_otherManager2_otherManager_secFileNumber': 'otherManager2SecFileNumber',
    'formData_summaryPage_otherManagers2Info_otherManager2_sequenceNumber': 'otherManager2SequenceNumber',
    'formData_summaryPage_tableEntryTotal': 'tableEntryTotal',
    'formData_summaryPage_tableValueTotal': 'tableValueTotal',
    'headerData_filerInfo_denovoRequest': 'denovoRequest',
    'headerData_filerInfo_filer_credentials_ccc': 'filerCredentialsCCC',
    'headerData_filerInfo_filer_credentials_cik': 'filerCredentialsCIK',
    'headerData_filerInfo_filer_fileNumber': 'filerFileNumber',
    'headerData_filerInfo_flags_confirmingCopyFlag': 'confirmingCopyFlag',
    'headerData_filerInfo_flags_overrideInternetFlag': 'overrideInternetFlag',
    'headerData_filerInfo_flags_returnCopyFlag': 'returnCopyFlag',
    'headerData_filerInfo_liveTestFlag': 'liveTestFlag',
    'headerData_filerInfo_periodOfReport': 'periodOfReport',
    'headerData_submissionType': 'submissionType',
    'schemaLocation': 'schemaLocation',
    'schemaVersion': 'schemaVersion'
}

mapping_information_table = {
    'infoTable': 'infoTable',
    'infoTable_cusip': 'cusip',
    'infoTable_figi': 'figi',
    'infoTable_investmentDiscretion': 'investmentDiscretion',
    'infoTable_nameOfIssuer': 'nameOfIssuer',
    'infoTable_otherManager': 'otherManager',
    'infoTable_putCall': 'putCall',
    'infoTable_shrsOrPrnAmt_sshPrnamt': 'sharesPrincipalAmount',
    'infoTable_shrsOrPrnAmt_sshPrnamtType': 'sharesPrincipalAmountType',
    'infoTable_titleOfClass': 'titleOfClass',
    'infoTable_value': 'value',
    'infoTable_votingAuthority_None': 'votingAuthorityNone',
    'infoTable_votingAuthority_Shared': 'votingAuthorityShared',
    'infoTable_votingAuthority_Sole': 'votingAuthoritySole',
    'schemaLocation': 'schemaLocation'
}

mapping_metadata_sbsef = {
    'formData_principalInfo_amendedItemsList': 'amendedItemsList',
    'formData_principalInfo_applicantName': 'applicantName',
    'formData_principalInfo_city': 'city',
    'formData_principalInfo_stateOrCountry': 'stateOrCountry',
    'formData_principalInfo_street1': 'street1',
    'formData_principalInfo_street2': 'street2',
    'formData_principalInfo_zipCode': 'zipCode',
    'headerData_filerInfo_filer_filerCredentials_ccc': 'filerCredentialsCCC',
    'headerData_filerInfo_filer_filerCredentials_cik': 'filerCredentialsCIK',
    'headerData_filerInfo_flags_overrideInternetFlag': 'overrideInternetFlag',
    'headerData_filerInfo_liveTestFlag': 'liveTestFlag',
    'headerData_submissionType': 'submissionType'
}

mapping_metadata_24f_2nt = {
    'headerData_filerInfo_filer_fileNumber' : 'filerNumber',
    'headerData_filerInfo_filer_issuerCredentials_ccc' : 'issuerCredentialsCCC',
    'headerData_filerInfo_filer_issuerCredentials_cik' : 'issuerCredentialsCIK',
    'headerData_filerInfo_flags_confirmingCopyFlag' : 'confirmingCopyFlag',
    'headerData_filerInfo_flags_overrideInternetFlag' : 'overrideInternetFlag',
    'headerData_filerInfo_investmentCompanyType' : 'investmentCompanyType',
    'headerData_filerInfo_liveTestFlag' : 'liveTestFlag',
    'headerData_submissionType' : 'submissionType',
    'schemaLocation' : 'schemaLocation',
    'schemaVersion' : 'schemaVersion'
}

mapping_metadata_24f_2nt = {
    'item1_addressOfIssuer_city': 'issuerCity',
    'item1_addressOfIssuer_country': 'issuerCountry',
    'item1_addressOfIssuer_state': 'issuerState',
    'item1_addressOfIssuer_street1': 'issuerStreet1',
    'item1_addressOfIssuer_street2': 'issuerStreet2',
    'item1_addressOfIssuer_zipCode': 'issuerZipCode',
    'item1_nameOfIssuer': 'issuerName',
    'item2_reportClassName_annualClassNameInfo_className': 'reportClassName',
    'item2_reportClassName_rptIncludeAllFlag': 'reportClassIncludeAllFlag',
    'item2_reportClass_annualClassInfo': 'reportClassInfo',
    'item2_reportClass_annualClassInfo_classId': 'reportClassId',
    'item2_reportClass_annualClassInfo_className': 'reportClass',
    'item2_reportClass_rptIncludeAllClassesFlag': 'reportIncludeAllClassesFlag',
    'item2_reportSeriesClass_rptIncludeAllSeriesFlag': 'reportIncludeAllSeriesFlag',
    'item2_reportSeriesClass_rptSeriesClassInfo': 'reportSeriesClassInfo',
    'item2_reportSeriesClass_rptSeriesClassInfo_classInfo': 'seriesClassInfo',
    'item2_reportSeriesClass_rptSeriesClassInfo_classInfo_classId': 'seriesClassId',
    'item2_reportSeriesClass_rptSeriesClassInfo_classInfo_className': 'seriesClassName',
    'item2_reportSeriesClass_rptSeriesClassInfo_includeAllClassesFlag': 'seriesIncludeAllClassesFlag',
    'item2_reportSeriesClass_rptSeriesClassInfo_seriesId': 'seriesId',
    'item2_reportSeriesClass_rptSeriesClassInfo_seriesName': 'seriesName',
    'item3_investmentCompActFileNo': 'investmentCompanyActFileNumber',
    'item3_securitiesActFileNumbers_securitiesActFileNo': 'securitiesActFileNumber',
    'item3_securitiesActFileNumbers_securitiesActFileNo_fileNumber': 'securitiesActFileNumberValue',
    'item4_isThisFormBeingFiledLate': 'isFiledLate',
    'item4_isThisTheLastTimeIssuerFilingThisForm': 'isLastFiling',
    'item4_lastDayOfFiscalYear': 'fiscalYearEndDate',
    'item5_aggregatePriceOfSecuritiesRedeemedOrRepurchasedAnyPrior': 'aggregatePriceRedeemedOrRepurchasedPrior',
    'item5_aggregatePriceOfSecuritiesRedeemedOrRepurchasedInFiscalYear': 'aggregatePriceRedeemedOrRepurchasedFiscalYear',
    'item5_aggregateSalePriceOfSecuritiesSold': 'aggregateSalePriceSold',
    'item5_multiplierForDeterminingRegistrationFee': 'registrationFeeMultiplier',
    'item5_netSales': 'netSales',
    'item5_redemptionCreditsAvailableForUseInFutureYears': 'redemptionCreditsForFutureYears',
    'item5_registrationFeeDue': 'registrationFeeDue',
    'item5_seriesOrClassId': 'seriesOrClassId',
    'item5_totalAvailableRedemptionCredits': 'totalAvailableRedemptionCredits',
    'item6_interestDue': 'interestDue',
    'item7_totalOfRegistrationFeePlusAnyInterestDue': 'totalRegistrationFeeAndInterest',
    'item8_explanatoryNotes': 'explanatoryNotes',
    'signature_nameAndTitle': 'signatureNameAndTitle',
    'signature_signature': 'signature',
    'signature_signatureDate': 'signatureDate'
}

mapping_metadata_144 = {
    'filerInfo_filer_filerCredentials_ccc' : 'filerCredentialsCCC',
    'filerInfo_filer_filerCredentials_cik' : 'filerCredentialsCIK',
    'filerInfo_liveTestFlag' : 'liveTestFlag',
    'previousAccessionNumber' : 'previousAccessionNumber',
    'submissionType' : 'submissionType',
    'nothingToReportFlagOnSecuritiesSoldInPast3Months': 'noSecuritiesSoldInPast3Months',
    'remarks': 'remarks',
}

mapping_signatures_144 = {
    'noticeDate': 'noticeDate',
    'planAdoptionDates_planAdoptionDate': 'planAdoptionDate',
    'signature': 'signature',
}

mapping_issuer_info_144 = {
    'issuerAddress_city': 'issuerCity',
    'issuerAddress_stateOrCountry': 'issuerStateOrCountry',
    'issuerAddress_street1': 'issuerStreet1',
    'issuerAddress_street2': 'issuerStreet2',
    'issuerAddress_zipCode': 'issuerZipCode',
    'issuerCik': 'issuerCIK',
    'issuerContactPhone': 'issuerContactPhone',
    'issuerName': 'issuerName',
    'nameOfPersonForWhoseAccountTheSecuritiesAreToBeSold': 'securitySeller',
    'relationshipsToIssuer_relationshipToIssuer': 'relationshipToIssuer',
    'secFileNumber': 'issuerSecFileNumber',
}
mapping_securities_information_144 = {
    'aggregateMarketValue': 'aggregateMarketValue',
    'approxSaleDate': 'approximateSaleDate',
    'brokerOrMarketmakerDetails_address_city': 'brokerCity',
    'brokerOrMarketmakerDetails_address_stateOrCountry': 'brokerStateOrCountry',
    'brokerOrMarketmakerDetails_address_street1': 'brokerStreet1',
    'brokerOrMarketmakerDetails_address_street2': 'brokerStreet2',
    'brokerOrMarketmakerDetails_address_zipCode': 'brokerZipCode',
    'brokerOrMarketmakerDetails_name': 'brokerName',
    'noOfUnitsOutstanding': 'numberOfUnitsOutstanding',
    'noOfUnitsSold': 'numberOfUnitsSold',
    'securitiesClassTitle': 'securitiesClassTitle',
    'securitiesExchangeName': 'securitiesExchangeName',
}
mapping_securities_sold_last_3_months_144 = {
    'amountOfSecuritiesSold': 'amountOfSecuritiesSoldPast3Months',
    'grossProceeds': 'grossProceedsPast3Months',
    'saleDate': 'saleDatePast3Months',
    'securitiesClassTitle': 'securitiesClassTitlePast3Months',
    'sellerDetails_address_city': 'sellerCityPast3Months',
    'sellerDetails_address_stateOrCountry': 'sellerStateOrCountryPast3Months',
    'sellerDetails_address_street1': 'sellerStreet1Past3Months',
    'sellerDetails_address_street2': 'sellerStreet2Past3Months',
    'sellerDetails_address_zipCode': 'sellerZipCodePast3Months',
    'sellerDetails_name': 'sellerNamePast3Months',
}



mapping_securities_to_be_sold_144 = {
    'acquiredDate': 'securitiesAcquiredDate',
    'amountOfSecuritiesAcquired': 'amountOfSecuritiesAcquired',
    'donarAcquiredDate': 'donorAcquiredDate',
    'isGiftTransaction': 'isGiftTransaction',
    'nameOfPersonfromWhomAcquired': 'acquiredFromName',
    'natureOfAcquisitionTransaction': 'acquisitionTransactionNature',
    'natureOfPayment': 'paymentNature',
    'paymentDate': 'paymentDate',
    'securitiesClassTitle': 'securitiesToBeSoldClassTitle'
}

mapping_25nse = {
    'descriptionClassSecurity': 'securityClassDescription',
    'exchange_cik': 'exchangeCIK',
    'exchange_entityName': 'exchangeName',
    'issuer_address_city': 'issuerCity',
    'issuer_address_stateOrCountry': 'issuerStateOrCountry',
    'issuer_address_stateOrCountryCode': 'issuerStateOrCountryCode',
    'issuer_address_street1': 'issuerStreet1',
    'issuer_address_street2': 'issuerStreet2',
    'issuer_address_zipCode': 'issuerZipCode',
    'issuer_cik': 'issuerCIK',
    'issuer_entityName': 'issuerName',
    'issuer_fileNumber': 'issuerFileNumber',
    'issuer_telephoneNumber': 'issuerTelephoneNumber',
    'ruleProvision': 'ruleProvision',
    'schemaVersion': 'schemaVersion',
    'signatureData_signatureDate': 'signatureDate',
    'signatureData_signatureName': 'signatureName',
    'signatureData_signatureTitle': 'signatureTitle'
}

mapping_metadata_c = {
    'filerInfo_filer_fileNumber' : 'filerNumber',
    'filerInfo_filer_filerCredentials_filerCcc' : 'filerCCC',
    'filerInfo_filer_filerCredentials_filerCik' : 'filerCIK',
    'filerInfo_flags_confirmingCopyFlag' : 'confirmingCopyFlag',
    'filerInfo_flags_overrideInternetFlag' : 'overrideInternetFlag',
    'filerInfo_flags_returnCopyFlag' : 'returnCopyFlag',
    'filerInfo_liveTestFlag' : 'liveTestFlag',
    'filerInfo_period' : 'period',
    'submissionType' : 'submissionType'
}

mapping_annual_disclosure_c = {
    'actReceivedMostRecentFiscalYear': 'actReceivedCurrentYear',
    'actReceivedPriorFiscalYear': 'actReceivedPriorYear',
    'cashEquiMostRecentFiscalYear': 'cashEquivalentsCurrentYear',
    'cashEquiPriorFiscalYear': 'cashEquivalentsPriorYear',
    'costGoodsSoldMostRecentFiscalYear': 'costOfGoodsSoldCurrentYear',
    'costGoodsSoldPriorFiscalYear': 'costOfGoodsSoldPriorYear',
    'currentEmployees': 'currentEmployees',
    'issueJurisdictionSecuritiesOffering': 'securitiesOfferingJurisdiction',
    'longTermDebtMostRecentFiscalYear': 'longTermDebtCurrentYear',
    'longTermDebtPriorFiscalYear': 'longTermDebtPriorYear',
    'netIncomeMostRecentFiscalYear': 'netIncomeCurrentYear',
    'netIncomePriorFiscalYear': 'netIncomePriorYear',
    'revenueMostRecentFiscalYear': 'revenueCurrentYear',
    'revenuePriorFiscalYear': 'revenuePriorYear',
    'shortTermDebtMostRecentFiscalYear': 'shortTermDebtCurrentYear',
    'shortTermDebtPriorFiscalYear': 'shortTermDebtPriorYear',
    'taxPaidMostRecentFiscalYear': 'taxPaidCurrentYear',
    'taxPaidPriorFiscalYear': 'taxPaidPriorYear',
    'totalAssetMostRecentFiscalYear': 'totalAssetsCurrentYear',
    'totalAssetPriorFiscalYear': 'totalAssetsPriorYear'
}

mapping_issuer_info_c = {
    'coIssuers_coIssuerInfo': 'coIssuerInfo',
    'coIssuers_coIssuerInfo_coIssuerAddress_city': 'coIssuerCity',
    'coIssuers_coIssuerInfo_coIssuerAddress_stateOrCountry': 'coIssuerStateOrCountry',
    'coIssuers_coIssuerInfo_coIssuerAddress_street1': 'coIssuerStreet1',
    'coIssuers_coIssuerInfo_coIssuerAddress_street2': 'coIssuerStreet2',
    'coIssuers_coIssuerInfo_coIssuerAddress_zipCode': 'coIssuerZipCode',
    'coIssuers_coIssuerInfo_coIssuerCik': 'coIssuerCIK',
    'coIssuers_coIssuerInfo_coIssuerLegalStatus_dateIncorporation': 'coIssuerIncorporationDate',
    'coIssuers_coIssuerInfo_coIssuerLegalStatus_jurisdictionOrganization': 'coIssuerJurisdiction',
    'coIssuers_coIssuerInfo_coIssuerLegalStatus_legalStatusForm': 'coIssuerLegalStatusForm',
    'coIssuers_coIssuerInfo_coIssuerWebsite': 'coIssuerWebsite',
    'coIssuers_coIssuerInfo_isEdgarFiler': 'coIssuerIsEdgarFiler',
    'coIssuers_coIssuerInfo_nameOfCoIssuer': 'coIssuerName',
    'commissionCik': 'commissionCIK',
    'commissionFileNumber': 'commissionFileNumber',
    'companyName': 'companyName',
    'crdNumber': 'crdNumber',
    'isAmendment': 'isAmendment',
    'isCoIssuer': 'isCoIssuer',
    'issuerInfo_issuerAddress_city': 'issuerCity',
    'issuerInfo_issuerAddress_stateOrCountry': 'issuerStateOrCountry',
    'issuerInfo_issuerAddress_street1': 'issuerStreet1',
    'issuerInfo_issuerAddress_street2': 'issuerStreet2',
    'issuerInfo_issuerAddress_zipCode': 'issuerZipCode',
    'issuerInfo_issuerWebsite': 'issuerWebsite',
    'issuerInfo_legalStatus_dateIncorporation': 'issuerIncorporationDate',
    'issuerInfo_legalStatus_jurisdictionOrganization': 'issuerJurisdiction',
    'issuerInfo_legalStatus_legalStatusForm': 'issuerLegalStatusForm',
    'issuerInfo_legalStatus_legalStatusOtherDesc': 'issuerLegalStatusOtherDescription',
    'issuerInfo_nameOfIssuer': 'issuerName',
    'natureOfAmendment': 'amendmentNature',
    'progressUpdate': 'progressUpdate'
}

mapping_offering_info_c = {
    'compensationAmount': 'compensationAmount',
    'deadlineDate': 'deadlineDate',
    'descOverSubscription': 'overSubscriptionDescription',
    'financialInterest': 'financialInterest',
    'maximumOfferingAmount': 'maximumOfferingAmount',
    'noOfSecurityOffered': 'numberOfSecuritiesOffered',
    'offeringAmount': 'offeringAmount',
    'overSubscriptionAccepted': 'overSubscriptionAccepted',
    'overSubscriptionAllocationType': 'overSubscriptionAllocationType',
    'price': 'price',
    'priceDeterminationMethod': 'priceDeterminationMethod',
    'securityOfferedOtherDesc': 'securityOfferedOtherDescription',
    'securityOfferedType': 'securityOfferedType'
}

mapping_signature_info_c = {
    'issuerSignature_issuer': 'signingIssuer',
    'issuerSignature_issuerSignature': 'issuerSignature',
    'issuerSignature_issuerTitle': 'issuerSignatureTitle',
    'signaturePersons_signaturePerson': 'signaturePerson',
    'signaturePersons_signaturePerson_personSignature': 'personSignature',
    'signaturePersons_signaturePerson_personTitle': 'personTitle',
    'signaturePersons_signaturePerson_signatureDate': 'signatureDate'
}

mapping_metadata_cfportal = {
    'filerInfo_filer_filerCredentials_filerCcc' : 'filerCCC',
    'filerInfo_filer_filerCredentials_filerCik' : 'filerCIK',
    'filerInfo_flags_overrideInternetFlag' : 'overrideInternetFlag',
    'filerInfo_flags_returnCopyFlag' : 'returnCopyFlag',
    'submissionType' : 'submissionType'

}