# Assets dictionary mapping
assets_dict_ex102_abs = {
    'assetNumber': 'assetNumber',
    'DefeasedStatusCode': 'DefeasedStatusCode',
    'defeasanceOptionStartDate': 'defeasanceOptionStartDate',
    'mostRecentDebtServiceCoverageNetOperatingIncomePercentage': 'mostRecentDebtServiceCoverageNetOperatingIncomePercentage',
    'mostRecentDebtServiceAmount': 'mostRecentDebtServiceAmount',
    'debtServiceCoverageSecuritizationCode': 'debtServiceCoverageSecuritizationCode',
    'debtServiceCoverageNetOperatingIncomeSecuritizationPercentage': 'debtServiceCoverageNetOperatingIncomeSecuritizationPercentage',
    'valuationSecuritizationDate': 'valuationSecuritizationDate',
    'physicalOccupancySecuritizationPercentage': 'physicalOccupancySecuritizationPercentage',
    'revenueSecuritizationAmount': 'revenueSecuritizationAmount',
    'valuationSourceSecuritizationCode': 'valuationSourceSecuritizationCode',
    'financialsSecuritizationDate': 'financialsSecuritizationDate',
    'mostRecentNetCashFlowAmount': 'mostRecentNetCashFlowAmount',
    'operatingExpensesAmount': 'operatingExpensesAmount',
    'operatingExpensesSecuritizationAmount': 'operatingExpensesSecuritizationAmount',
    'netOperatingIncomeNetCashFlowSecuritizationCode': 'netOperatingIncomeNetCashFlowSecuritizationCode',
    'mostRecentValuationSourceCode': 'mostRecentValuationSourceCode',
    'mostRecentDebtServiceCoverageNetCashFlowpercentage': 'mostRecentDebtServiceCoverageNetCashFlowpercentage',
    'debtServiceCoverageNetCashFlowSecuritizationPercentage': 'debtServiceCoverageNetCashFlowSecuritizationPercentage',
    'mostRecentAnnualLeaseRolloverReviewDate': 'mostRecentAnnualLeaseRolloverReviewDate',
    'mostRecentRevenueAmount': 'mostRecentRevenueAmount',
    'mostRecentPhysicalOccupancyPercentage': 'mostRecentPhysicalOccupancyPercentage',
    'mostRecentNetOperatingIncomeAmount': 'mostRecentNetOperatingIncomeAmount',
    'netOperatingIncomeSecuritizationAmount': 'netOperatingIncomeSecuritizationAmount',
    'netOperatingIncomeNetCashFlowCode': 'netOperatingIncomeNetCashFlowCode',
    'mostRecentFinancialsStartDate': 'mostRecentFinancialsStartDate',
    'mostRecentFinancialsEndDate': 'mostRecentFinancialsEndDate',
    'accession': 'accession',
    'valuationSecuritizationAmount': 'valuationSecuritizationAmount',
    'mostRecentValuationDate': 'mostRecentValuationDate',
    'mostRecentValuationAmount': 'mostRecentValuationAmount',
    'mostRecentDebtServiceCoverageCode': 'mostRecentDebtServiceCoverageCode',
    'netCashFlowFlowSecuritizationAmount': 'netCashFlowFlowSecuritizationAmount'
}

# Properties dictionary mapping
properties_dict_ex102_abs = {
    'unitsBedsRoomsNumber': 'unitsBedsRoomsNumber',
    'propertyCounty': 'propertyCounty',
    'squareFeetLargestTenantNumber': 'squareFeetLargestTenantNumber',
    'netRentableSquareFeetNumber': 'netRentableSquareFeetNumber',
    'leaseExpirationThirdLargestTenantDate': 'leaseExpirationThirdLargestTenantDate',
    'leaseExpirationLargestTenantDate': 'leaseExpirationLargestTenantDate',
    'propertyZip': 'propertyZip',
    'squareFeetThirdLargestTenantNumber': 'squareFeetThirdLargestTenantNumber',
    'propertyStatusCode': 'propertyStatusCode',
    'propertyState': 'propertyState',
    'yearBuiltNumber': 'yearBuiltNumber',
    'propertyCity': 'propertyCity',
    'propertyName': 'propertyName',
    'propertyAddress': 'propertyAddress',
    'yearLastRenovated': 'yearLastRenovated',
    'leaseExpirationSecondLargestTenantDate': 'leaseExpirationSecondLargestTenantDate',
    'thirdLargestTenant': 'thirdLargestTenant',
    'unitsBedsRoomsSecuritizationNumber': 'unitsBedsRoomsSecuritizationNumber',
    'propertyTypeCode': 'propertyTypeCode',
    'largestTenant': 'largestTenant',
    'squareFeetSecondLargestTenantNumber': 'squareFeetSecondLargestTenantNumber',
    'netRentableSquareFeetSecuritizationNumber': 'netRentableSquareFeetSecuritizationNumber',
    'secondLargestTenant': 'secondLargestTenant'
}